# Generated by Django 5.2.4 on 2025-09-22 02:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobis_username', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('between_street', models.CharField(blank=True, max_length=255, null=True)),
                ('num_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('num_int', models.CharField(blank=True, max_length=10, null=True)),
                ('cologne', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DIF', 'Ciudad de México'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], default='DIF', max_length=3, null=True, verbose_name='Estado')),
                ('country', models.CharField(default='México', max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sobis_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('APPROVED', 'Aprobado'), ('DESIGN', 'Diseño'), ('DEVELOPMENT', 'Programación'), ('DEPLOYMENT', 'Despliegue'), ('COMPLETED', 'Completado'), ('ARCHIVED', 'Archivado')], default='NEW', max_length=20, verbose_name='Estatus')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Tarjeta de crédito'), ('paypal', 'PayPal'), ('mp', 'Mercado Pago'), ('transfer', 'Transferencia'), ('cash', 'Efectivo')], default='credit_card', max_length=50)),
                ('quote', models.FileField(blank=True, null=True, upload_to='quotes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('terms', models.TextField(blank=True, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('token', models.UUIDField(blank=True, editable=False, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='crm.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.customer')),
            ],
        ),
    ]
