# Generated by Django 5.2.4 on 2025-09-22 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
